name: Build Unity Project for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unityVersion: 2020.3.19f1
        modules: 'all'

    - name: Build Unity project for Windows
      uses: game-ci/unity-builder@v4
      with:
        targetPlatform: StandaloneWindows64

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: Build/
