name: Unity Test and Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  upload_results:
    name: Upload Test and Coverage Results
    runs-on: ubuntu-latest
    needs:
      - test
